import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // Everything here is code this project does not author. Between them these
    // entries took `bun run lint` from twenty minutes and permanently red to
    // six seconds and green, without silencing a single finding about our own
    // source.
    //
    //   `.netlify`  — the time sink. `NITRO_PRESET=netlify bun run build`
    //     writes a bundled server here mirroring `.output/server`: a 0.6 MB
    //     router bundle, 0.4 MB of framer-motion. Prettier reformatting
    //     megabytes of generated bundle is pathologically slow. `dist`,
    //     `.output` and `.vinxi` were listed from the start; this one was
    //     missed because it only exists once someone runs the netlify preset
    //     locally.
    //
    //   `.claude/` — the noise. ~100 installed skill and agent packages, 840
    //     tracked files written by other people. They produced 197 MB of
    //     prettier diffs, none of it about this codebase, which is how a real
    //     `no-unused-labels` error in `src/` went unread long enough for every
    //     unknown industry slug to answer 200. See `scripts/qa-status.mjs`.
    //
    //   `.qa-tmp/`, `scripts/.tmp/` — scratch, not one tracked file between
    //     them. `scripts/.tmp/` is 17 throwaway measurement scripts from
    //     earlier phases.
    //
    //   The two Supabase files — generated by Lovable into the source tree;
    //     `previewAuthStorage.ts` opens with "This file is automatically
    //     generated. Do not edit it directly." Their findings are unactionable,
    //     because fixing one means editing a file the next sync overwrites, and
    //     a linter that reports faults nobody may repair just teaches people to
    //     stop reading it. Excluded by name: the other four files in that
    //     directory are hand-written and stay linted.
    ignores: [
      "dist",
      ".output",
      ".netlify",
      ".vinxi",
      ".claude/**",
      ".qa-tmp/**",
      "scripts/.tmp/**",
      "src/integrations/supabase/types.ts",
      "src/integrations/supabase/previewAuthStorage.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
