import { chromium } from 'playwright-core';
const [, , url, out, width, selector, nth] = process.argv;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: +width, height: 1000 }, deviceScaleFactor: 2 });
await p.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
await p.evaluate(async () => { const s = innerHeight*0.5;
  for (let y=0;y<document.body.scrollHeight;y+=s){scrollTo(0,y);await new Promise(r=>setTimeout(r,120));} });
const el = p.locator(selector).nth(+(nth ?? 0));
await el.scrollIntoViewIfNeeded();
await p.waitForTimeout(1200);
await el.screenshot({ path: out });
await b.close();
