/**
 * Walks every image under src/assets/ and writes docs/image-inventory.md.
 *
 * Dimensions are read straight from the file headers rather than by decoding —
 * a 3 MB WebP costs a 32-byte read this way. Handles the three formats actually
 * present in the tree (WebP incl. VP8/VP8L/VP8X, PNG, JPEG) plus the
 * `.asset.json` CDN pointers, which have no local bytes to measure at all.
 *
 * Run: bun scripts/inventory-assets.ts
 */
import { readdirSync, statSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, relative, extname, basename, dirname } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const ASSETS = join(ROOT, "src/assets");
const OUT = join(ROOT, "docs/image-inventory.md");

type Info = {
  path: string;
  format: string;
  width: number | null;
  height: number | null;
  bytes: number;
  alpha: boolean | null;
  has800: boolean;
  remote: boolean;
};

function walk(dir: string, acc: string[] = []): string[] {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p, acc);
    else acc.push(p);
  }
  return acc;
}

/** PNG: IHDR is always the first chunk — width/height/colour-type at fixed offsets. */
function png(b: Buffer) {
  const colourType = b[25];
  // 4 = grey+alpha, 6 = RGBA, 3 = palette (may carry tRNS)
  const alpha = colourType === 4 || colourType === 6 || (colourType === 3 && b.includes(Buffer.from("tRNS")));
  return { width: b.readUInt32BE(16), height: b.readUInt32BE(20), alpha };
}

/** JPEG: scan the marker chain for a SOFn frame header. Never has alpha. */
function jpeg(b: Buffer) {
  let i = 2;
  while (i < b.length - 9) {
    if (b[i] !== 0xff) { i++; continue; }
    const marker = b[i + 1];
    // SOF0-SOF15 except the non-frame markers DHT(c4), JPG(c8), DAC(cc)
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      return { width: b.readUInt16BE(i + 7), height: b.readUInt16BE(i + 5), alpha: false };
    }
    i += 2 + b.readUInt16BE(i + 2);
  }
  return { width: null, height: null, alpha: false };
}

/** WebP: three sub-formats, each storing its size differently. */
function webp(b: Buffer) {
  const fourcc = b.toString("ascii", 12, 16);
  if (fourcc === "VP8X") {
    return {
      width: 1 + (b[24] | (b[25] << 8) | (b[26] << 16)),
      height: 1 + (b[27] | (b[28] << 8) | (b[29] << 16)),
      alpha: (b[20] & 0x10) !== 0,
    };
  }
  if (fourcc === "VP8L") {
    const bits = b.readUInt32LE(21);
    return {
      width: 1 + (bits & 0x3fff),
      height: 1 + ((bits >> 14) & 0x3fff),
      alpha: ((bits >> 28) & 1) !== 0,
    };
  }
  if (fourcc === "VP8 ") {
    // Lossy: 3-byte start code 0x9d012a precedes the 14-bit dimensions.
    const s = b.indexOf(Buffer.from([0x9d, 0x01, 0x2a]), 20);
    if (s > 0) {
      return {
        width: b.readUInt16LE(s + 3) & 0x3fff,
        height: b.readUInt16LE(s + 5) & 0x3fff,
        alpha: false,
      };
    }
  }
  return { width: null, height: null, alpha: null };
}

function ratio(w: number | null, h: number | null) {
  if (!w || !h) return "—";
  const g = (a: number, b: number): number => (b ? g(b, a % b) : a);
  const d = g(w, h);
  const rw = w / d, rh = h / d;
  // Only print an exact integer ratio when it is legible; otherwise decimal.
  return rw <= 32 && rh <= 32 ? `${rw}:${rh}` : (w / h).toFixed(2);
}

const files = walk(ASSETS).sort();
const rows: Info[] = [];

for (const f of files) {
  const ext = extname(f).toLowerCase();
  const rel = relative(ROOT, f);
  const bytes = statSync(f).size;

  if (f.endsWith(".asset.json")) {
    const j = JSON.parse(readFileSync(f, "utf8"));
    rows.push({
      path: rel, format: "CDN pointer", width: j.width ?? null, height: j.height ?? null,
      bytes, alpha: null, has800: false, remote: true,
    });
    continue;
  }
  if (![".webp", ".png", ".jpg", ".jpeg"].includes(ext)) continue;

  const head = Buffer.alloc(Math.min(bytes, 65536));
  const fd = require("node:fs").openSync(f, "r");
  require("node:fs").readSync(fd, head, 0, head.length, 0);
  require("node:fs").closeSync(fd);

  const d = ext === ".png" ? png(head) : ext === ".webp" ? webp(head) : jpeg(head);
  const stem = basename(f, ext);
  rows.push({
    path: rel, format: ext.slice(1), width: d.width, height: d.height, bytes,
    alpha: d.alpha, has800: existsSync(join(dirname(f), `${stem}@800${ext}`)),
    remote: false,
  });
}

const kb = (n: number) => (n < 1024 * 1024 ? `${Math.round(n / 1024)} KB` : `${(n / 1024 / 1024).toFixed(1)} MB`);
const local = rows.filter((r) => !r.remote && !r.path.includes("@800"));
const variants = rows.filter((r) => r.path.includes("@800"));
const remote = rows.filter((r) => r.remote);

let md = `# Image inventory

Generated by \`bun scripts/inventory-assets.ts\`. Do not edit the generated tables by hand —
edit the **Subject** and **Proposed slot** columns in the "Needs sign-off" section instead,
which the script leaves alone.

- **${local.length}** local source images
- **${variants.length}** \`@800\` responsive variants
- **${remote.length}** \`.asset.json\` CDN pointers (no local bytes)
- Total local weight: **${kb(rows.filter((r) => !r.remote).reduce((a, r) => a + r.bytes, 0))}**

## Local source images

| File | Format | Dimensions | Ratio | Size | Alpha | @800 |
|---|---|---|---|---|---|---|
`;
for (const r of local) {
  const dim = r.width && r.height ? `${r.width}×${r.height}` : "—";
  md += `| \`${r.path.replace("src/assets/", "")}\` | ${r.format} | ${dim} | ${ratio(r.width, r.height)} | ${kb(r.bytes)} | ${r.alpha === null ? "—" : r.alpha ? "**yes** (cutout)" : "no"} | ${r.has800 ? "yes" : "—"} |\n`;
}

md += `\n## \`@800\` variants\n\n| File | Dimensions | Size |\n|---|---|---|\n`;
for (const r of variants) {
  md += `| \`${r.path.replace("src/assets/", "")}\` | ${r.width && r.height ? `${r.width}×${r.height}` : "—"} | ${kb(r.bytes)} |\n`;
}

md += `\n## CDN pointers (\`.asset.json\`)\n\nThese resolve to Lovable's CDN. They render today but exist nowhere in the repo —
if that project is unpublished or rate-limited they vanish from the Netlify site.\n\n| File | Dimensions |\n|---|---|\n`;
for (const r of remote) {
  md += `| \`${r.path.replace("src/assets/", "")}\` | ${r.width && r.height ? `${r.width}×${r.height}` : "—"} |\n`;
}

writeFileSync(OUT, md);
console.log(`${OUT}: ${local.length} sources, ${variants.length} variants, ${remote.length} pointers`);
