/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as PocRouteImport } from './routes/poc'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangPocRouteImport } from './routes/$lang/poc'
import { Route as LangServiceRouteImport } from './routes/$lang/service'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogIdRouteImport } from './routes/catalog.$id'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as LangCatalogIndexRouteImport } from './routes/$lang/catalog.index'
import { Route as LangCatalogIdRouteImport } from './routes/$lang/catalog.$id'
import { Route as LangIndustriesIndexRouteImport } from './routes/$lang/industries.index'
import { Route as LangIndustriesSlugRouteImport } from './routes/$lang/industries.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const PocRoute = PocRouteImport.update({
  id: '/poc',
  path: '/poc',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangPocRoute = LangPocRouteImport.update({
  id: '/poc',
  path: '/poc',
  getParentRoute: () => LangRoute,
} as any)
const LangServiceRoute = LangServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => LangRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIdRoute = CatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangCatalogIndexRoute = LangCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => LangRoute,
} as any)
const LangCatalogIdRoute = LangCatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => LangRoute,
} as any)
const LangIndustriesIndexRoute = LangIndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => LangRoute,
} as any)
const LangIndustriesSlugRoute = LangIndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/poc': typeof PocRoute
  '/service': typeof ServiceRoute
  '/$lang/poc': typeof LangPocRoute
  '/$lang/service': typeof LangServiceRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/$lang/catalog/$id': typeof LangCatalogIdRoute
  '/$lang/industries/$slug': typeof LangIndustriesSlugRoute
  '/$lang/catalog/': typeof LangCatalogIndexRoute
  '/$lang/industries/': typeof LangIndustriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/poc': typeof PocRoute
  '/service': typeof ServiceRoute
  '/$lang/poc': typeof LangPocRoute
  '/$lang/service': typeof LangServiceRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/$lang': typeof LangIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/$lang/catalog/$id': typeof LangCatalogIdRoute
  '/$lang/industries/$slug': typeof LangIndustriesSlugRoute
  '/$lang/catalog': typeof LangCatalogIndexRoute
  '/$lang/industries': typeof LangIndustriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/poc': typeof PocRoute
  '/service': typeof ServiceRoute
  '/$lang/poc': typeof LangPocRoute
  '/$lang/service': typeof LangServiceRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/$lang/catalog/$id': typeof LangCatalogIdRoute
  '/$lang/industries/$slug': typeof LangIndustriesSlugRoute
  '/$lang/catalog/': typeof LangCatalogIndexRoute
  '/$lang/industries/': typeof LangIndustriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/poc'
    | '/service'
    | '/$lang/poc'
    | '/$lang/service'
    | '/catalog/$id'
    | '/industries/$slug'
    | '/$lang/'
    | '/catalog/'
    | '/industries/'
    | '/$lang/catalog/$id'
    | '/$lang/industries/$slug'
    | '/$lang/catalog/'
    | '/$lang/industries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/poc'
    | '/service'
    | '/$lang/poc'
    | '/$lang/service'
    | '/catalog/$id'
    | '/industries/$slug'
    | '/$lang'
    | '/catalog'
    | '/industries'
    | '/$lang/catalog/$id'
    | '/$lang/industries/$slug'
    | '/$lang/catalog'
    | '/$lang/industries'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/poc'
    | '/service'
    | '/$lang/poc'
    | '/$lang/service'
    | '/catalog/$id'
    | '/industries/$slug'
    | '/$lang/'
    | '/catalog/'
    | '/industries/'
    | '/$lang/catalog/$id'
    | '/$lang/industries/$slug'
    | '/$lang/catalog/'
    | '/$lang/industries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  PocRoute: typeof PocRoute
  ServiceRoute: typeof ServiceRoute
  CatalogIdRoute: typeof CatalogIdRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc': {
      id: '/poc'
      path: '/poc'
      fullPath: '/poc'
      preLoaderRoute: typeof PocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/poc': {
      id: '/$lang/poc'
      path: '/poc'
      fullPath: '/$lang/poc'
      preLoaderRoute: typeof LangPocRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/service': {
      id: '/$lang/service'
      path: '/service'
      fullPath: '/$lang/service'
      preLoaderRoute: typeof LangServiceRouteImport
      parentRoute: typeof LangRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/catalog/': {
      id: '/$lang/catalog/'
      path: '/catalog'
      fullPath: '/$lang/catalog/'
      preLoaderRoute: typeof LangCatalogIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/catalog/$id': {
      id: '/$lang/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/$lang/catalog/$id'
      preLoaderRoute: typeof LangCatalogIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/industries/': {
      id: '/$lang/industries/'
      path: '/industries'
      fullPath: '/$lang/industries/'
      preLoaderRoute: typeof LangIndustriesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/industries/$slug': {
      id: '/$lang/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/$lang/industries/$slug'
      preLoaderRoute: typeof LangIndustriesSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangPocRoute: typeof LangPocRoute
  LangServiceRoute: typeof LangServiceRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCatalogIdRoute: typeof LangCatalogIdRoute
  LangIndustriesSlugRoute: typeof LangIndustriesSlugRoute
  LangCatalogIndexRoute: typeof LangCatalogIndexRoute
  LangIndustriesIndexRoute: typeof LangIndustriesIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangPocRoute: LangPocRoute,
  LangServiceRoute: LangServiceRoute,
  LangIndexRoute: LangIndexRoute,
  LangCatalogIdRoute: LangCatalogIdRoute,
  LangIndustriesSlugRoute: LangIndustriesSlugRoute,
  LangCatalogIndexRoute: LangCatalogIndexRoute,
  LangIndustriesIndexRoute: LangIndustriesIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  PocRoute: PocRoute,
  ServiceRoute: ServiceRoute,
  CatalogIdRoute: CatalogIdRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
